job_api:
    build: .
    links:
        - redis:redis
    environment:
      NODE_ENV: "production"
      DEBUG: "false"
      port: "3001"
    restart: unless-stopped
    ports:
      - "3001:3001"
redis:
    image: redis:3.2
    volumes:
      - "job_api-redis-volume:/data"
